font_family      JetBrainsMono Nerd Font
font_size        11.0

confirm_os_window_close 0
window_padding_width 6

background             #141218
foreground             #e6e0e9
cursor                 #d0bcff
selection_background   #ccc2dc

color0  #141218
color8  #49454e
color1  #f2b8b5
color9  #f2b8b5
color2  #a6e3a1
color10 #a6e3a1
color3  #f9e2af
color11 #f9e2af
color4  #d0bcff
color12 #d0bcff
color5  #ccc2dc
color13 #ccc2dc
color6  #94e2d5
color14 #94e2d5
color7  #cac4cf
color15 #e6e0e9

globinclude dank-*.conf
